### ISSUE TITLE
Add Authentication documentation is incorrect

### ISSUE THREAD

**Issue by BarcaJames** [taslangraham/tode-cli#18]
The add authentication section contain the same information for the create service section.
![image](https://user-images.githubusercontent.com/49459617/168339421-fea207bc-b6a1-4622-81f5-062bc1d41984.png)

**Comment by taslangraham** [comment]
@BarcaJames Thanks for highlighting this. I'll be updating it soon.

**Comment by taslangraham** [comment]
@BarcaJames I've update the docs -https://taslangraham.github.io/tode-cli-docs/#/Commands?id=add-authentication

**Comment by BarcaJames** [comment]
Wonderful!
