### ISSUE TITLE
Cannot find module 'rimraf' when executing command

### ISSUE THREAD

**Issue by andre-vidal** [taslangraham/tode-cli#4]
OS: Windows 10
tode-cli version: 0.2.10
node version: 14.16.1
command: `tode -h`
Result:
![image](https://user-images.githubusercontent.com/53495324/144614115-49c34680-fdba-45d2-8ef9-1c20a082a76e.png)

**Comment by taslangraham** [comment]
Thanks for reporting this issue.
It has been fixed in version 0.2.12
